const STATUS_CODE = {
    SUCCESS : 200,
    SOME_ERROR_OCCURRED : 500,
    INTERNAL_SERVER_ERROR : 500,
    PARAMETER_MISSING : 400,
    RECORDS_MISMATCH_1 : 201,
    RECORDS_MISMATCH_2 : 202,
    RECORDS_MISMATCH_3 : 203,
    RECORDS_MISMATCH_4 : 204,
    RECORDS_MISMATCH_5 : 205
}

module.exports = {
    STATUS_CODE : STATUS_CODE
}